In [ ]:
# Numpy

In [ ]:
# Numpy is a python library that is used for working with the array 
# Numpy stands for numerical python
# Numpy had a domain function of linear algebra , matrices , fourier transform
# Numpy is faster than the python list , because numpy array store at single location


In [4]:
# You need to first install the numpy before using it in your project

In [3]:
pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# once you installed then you need to import it in your project

In [5]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
# import is keyword numpy is module name 
# np is alias it mran it referring to the same thing and as is keyword for alias

[10 20 30 40]


In [6]:
import numpy as np
arr = np.array([10,20,30])
print(arr)

[10 20 30]


In [ ]:
# Creating the array 

In [ ]:
# Numpy is used with working with the array
# The array object in numpy is ndarray
# we can pass any tuple , list or array like function insdie the numpy

In [7]:
arr = np.array((1,2,3,4))
print(arr)

[1 2 3 4]


In [8]:
# Dimensions in array

In [9]:
# 0-D
# 1-D
# 2-D
# 3-D

In [10]:
# 0-D
arr = np.array(16)
print(arr)

16


In [11]:
# 1-D 
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [12]:
# 2-D 
arr = np.array([[10,20,30],[10,20,30]])
print(arr)

[[10 20 30]
 [10 20 30]]


In [26]:
arr = np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(arr)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]


In [18]:
# How to check the array dimensions
# to check the array dimension we can make use of ndim function


In [20]:
arr = np.array([10,20,30,40,50])
print(arr.ndim)

1


In [21]:
# Accessing the array element

In [22]:
# We can access the array index using the array index
# array index always starts with zero , than one and so on

In [23]:
arr = np.array([10,20,30,40,50])
print(arr[1])
# Here we accessed the first index element

20


In [24]:
# 2-D element access

In [25]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[1,2])

70


In [27]:
# Slicing

In [28]:
# slicing means taking element from one index to another given index

In [29]:
arr = np.array([10,20,30,40,50])
print(arr[1:3])

[20 30]


In [30]:
# slicing from first to given index

In [31]:
arr = np.array([10,20,30,40,50])
print(arr[:3])

[10 20 30]


In [32]:
# slicing from any particular index to last index

In [33]:
arr = np.array([10,20,30,40,50])
print(arr[3:])

[40 50]


In [34]:
# Return every other element

In [37]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[::3])

[10 40 70]


In [38]:
# Shape

In [39]:
# Shap of an array is the numerb of an a element in each dimensions

In [40]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)


[[1 2 3 4]
 [5 6 7 8]]


In [41]:
# Reshape array

In [42]:
# Reshape array means changing the shape of an array

In [49]:
arr = np.array ([10,20,30,40,50,60,70,80,90,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [10 11 12]]


In [50]:
# Join array

In [51]:
# join array me we have to join two array using the function called concatenate() 

In [52]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
arr = np.concatenate((arr1,arr2))
print(arr)

[10 20 30 40 50 60]


In [53]:
# Search

In [54]:
# serach is used to find the elemnt to that we make use of where() function

In [55]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


In [56]:
# Sort

In [57]:
# sort is used to sort the array either is ascendg or descending

In [58]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]
